version: '3.7'

services:
  picsift-api:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ./picsift-data:/app
    depends_on:
      - elasticsearch
      - mongo
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=screenshotDB
      - MONGO_COLLECTION=screenshots
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - STORAGE_PROVIDER=Backblaze

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

volumes:
  picsift-data:
  mongo-data:
  es-data:
