version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - "9200:9200"
    environment: ['ES_JAVA_OPTS=-Xms75m -Xmx75m','discovery.type=single-node','cluster.routing.allocation.disk.threshold_enabled=false','logger.level=INFO']
    ulimits:
      memlock: -1
      nofile: 65535
      nproc: 4096
    restart: on-failure
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    env_file:
      - .env
    networks:
      - picsift

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .env
    networks:
      - picsift

  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: on-failure
    depends_on:
      - elasticsearch
      - mongo
    env_file:
      - .env
    networks:
      - picsift

networks:
  picsift:

volumes:
  app:
  mongo-data:
  es-data:
