version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - "9200:9200"
    environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    env_file:
      - .env
    networks:
      - picsift

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .env
    networks:
      - picsift

  backend:
    build: .
    command: ["./wait-for-it.sh", "elasticsearch:9200", "--", "./wait-for-it.sh", "mongo:27017", "--", "python", "main.py"]
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - elasticsearch
      - mongo
    env_file:
      - .env
    networks:
      - picsift

networks:
  picsift:

volumes:
  app:
  mongo-data:
  es-data:
